config/routes.rb
Rails.application.routes.draw do
  
  get 'topics/new'
  get 'sessions/new'
  root 'pages#index' # controller#action
  get 'pages/help' # path
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :users # まとめて定義
  resources :topics # まとめて定義
  
  get    '/login',   to: 'sessions#new' # ログインするためのフォームを表示するページを取得, 転送<GET /URL sessions_controller_new_action>
  post   '/login',   to: 'sessions#create'# メールアドレス, パスワードを送信してもらい, データを元にSessionを作成, 処理を振り分け<POST /URL sessions_controller_create_action>
  delete '/logout',  to: 'sessions#destroy'# ログアウトでSessionを削除に処理を振り分け<DELETE /URL sessions_controller_destroy_action>
  
  get 'favorites/index' # path get = 取得
  post '/favorites', to: 'favorites#create' # post = 取得　path controller#action
  delete '/favorites', to: 'favorites#destroy' # delete = 削除 path controller#action
  
  get '/comments/:topic_id/new', to: 'comments#new', as: 'comments' # asを使い, ルーティングに名前を指定 comments_path
  post '/comments/:topic_id/create', to: 'comments#create', as: 'comments_create' # asを使い, ルーティングに名前を指定 comments_create_path
  resources :comments # まとめて定義
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates :user_id, presence: true # カラム, 空欄ではないか判断 Userテーブルのデータを参照するため, あらかじめUserテーブルのuser_idを<外部キー = 他のテーブルのプライマリキー(カラム)> 
  validates :description, presence: true # カラム, 空欄ではないか判断
  validates :image, presence: true # カラム, 空欄ではないか判断
  
  belongs_to :user # アソシエーション それぞれのTopicは1つのUserを持つ
  
  mount_uploader :image, ImageUploader
  
  has_many :favorites # # アソシエーション 1つのTopicは複数のFavoriteを持つ
  has_many :favorite_users, through: :favorites, source: 'user' # through(中間テーブル)を使うことで, Topicをいいねしている全てのUserを取得
  has_many :comments # アソシエーション 1つのUserは複数のCommentを持つ
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index # indexアクションを作成(リソース一覧を表示)
    @topics = Topic.all.includes(:favorite_users) # View(index.html.erb)を作成, 投稿一覧を表示できる
  end
  
  def new
    if logged_in? # ログイン状態でのみnewアクションにアクセス出来るように条件分岐
      @topic = Topic.new # form_forに渡すインスタンス変数(@topic) newメソッドで何も情報を持っていないので自動的にcreateアクションへ
    else
      redirect_to login_path, info: 'ログインして下さい' # info = 青
    end
  end
  
  def create # createアクションでリソースを追加しsaveメソッドを使用(保存), Controllerで保存されたインスタンス変数は,そのControllerに紐づくViewに値が渡される
    @topic = current_user.topics.new(topic_params)
    
    if @topic.save
      redirect_to topics_path, success: '投稿に成功しました' # success = 緑
    else
      flash.now[:danger] = "投稿に失敗しました" # danger = 赤
      render :new # 表示したいビュー(usersディレクトリ内のnew.html.erbが表示)
    end
  end
  
  private # クラス外からは呼び出せない
  def topic_params # ストロングパラメーター
    params.require(:topic).permit(:image, :description)
  end
end

app/views/topics/index.html.erb
<div class="topic-index-wrapper">
  <div class="container">
    <% @topics.each do |topic| %> <!--コントローラー内で@topics = Topic.allとして全てのトピックを取得, それがViewに渡ってここで一つ一つ取り出されてTopicに入る-->
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="topic-index-single">
            <h2 class="topic-author">
              <%= topic.user.name %> <!--TopicモデルとUserモデルは紐付いているので, topic.user.nameとすることでそのuserのnameプロパティが呼み出せる-->
            </h2>
            <%= image_tag topic.image.url %> <!--投稿された画像を表示-->
            <% if !topic.favorite_users.include?(current_user) %> <!--このTopicにログインしているユーザーのid(favorite_users)が存在しなかったら (includes? = 存在しているか確認する時に使う)-->
              <%= link_to favorites_path(topic_id: topic.id), method: :post do %> <!--pathにシンボルを与えて, link_toにパラメーターを渡す, params[:topic_id]にtopic.idが入る, routesにあるfavorites#createアクションに遷移した時に, いいねしたTopicのidを取得-->
                <%= image_tag 'icons/heart-black.png', class: 'topic-index-icon' %>
              <% end %>
            <% else %>
              <%= link_to favorites_path(topic_id: topic.id), method: :delete do %> <!--favorites#destroyアクションに遷移した時に, ハートをクリックするとfavoriteテーブルからカラムを削除-->
                <i class="fa fa-heart" aria-hidden="true"></i>
              <% end %>
            <% end %>
            <%= topic.favorite_users.count %> <!--いいねされた数を表示-->
              <%= link_to comments_path(topic_id: topic.id) do %>
                <%= image_tag 'icons/comment.png', class: 'topic-index-icon' %>
              <% end %>
            <p class="topic-text">
              <%= topic.description %> <!--画像の概要を表示-->
            </p>
            <h3>コメント</h3>
              <% topic.comments.each do |comment| %> <!--topic.commentsでそのtopicのコメントを取得-->
            <p class="topic-text">
              <%= comment.content %> <!--commentのcontent(カラム)-->
            </p>
              <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/topics/new.html.erb
<div class="topic-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">Add Picture</h1>
        <%= form_for @topic do |f| %> <!--topicクラスのインスタンス, form_for モデル do |f|とendで囲むことでモデル<@topic>のフォームを作成-->
          <div class="form-group">
            <%= f.label :image %> <!--labelタグを作成, image = カラム-->
            <%= f.file_field :image %> <!--ファイル選択ボックスを作成, image = カラム-->
          </div>
          
          <div class="form-group">
            <%= f.label :description %> <!--labelタグを作成, description = カラム-->
            <%= f.text_area :description, class: 'form-control' %> <!--テキストエリアを作成, description = カラム-->
          </div>
          
          <%= f.submit '投稿', class: 'btn btn-black btn-block' %> <!--送信ボタンを作成<投稿>-->
          
        <% end %>
        
        <%= link_to "投稿一覧", :controller => "topics", :action => "index" %>
        
      </div>
    </div>
  </div>
</div>