config/routes.rb
Rails.application.routes.draw do
  
  get 'topics/new'
  get 'sessions/new'
  root 'pages#index' # controller#action
  get 'pages/help' # path
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :users # まとめて定義
  resources :topics # まとめて定義
  
  get    '/login',   to: 'sessions#new' # ログインするためのフォームを表示するページを取得, 転送<GET /URL sessions_controller_new_action>
  post   '/login',   to: 'sessions#create'# メールアドレス, パスワードを送信してもらい, データを元にSessionを作成, 処理を振り分け<POST /URL sessions_controller_create_action>
  delete '/logout',  to: 'sessions#destroy'# ログアウトでSessionを削除に処理を振り分け<DELETE /URL sessions_controller_destroy_action>
  
  get 'favorites/index' # path get = 取得
  post '/favorites', to: 'favorites#create' # post = 取得　path controller#action
  delete '/favorites', to: 'favorites#destroy' # delete = 削除 path controller#action
  
  get '/comments/:topic_id/new', to: 'comments#new', as: 'comments' # asを使い, ルーティングに名前を指定 comments_path
  post '/comments/:topic_id/create', to: 'comments#create', as: 'comments_create' # asを使い, ルーティングに名前を指定 comments_create_path
  resources :comments # まとめて定義
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Juventgram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>" role="alert"><%= value %></div>
    <% end %>
    
    <nav class="navbar navbar-default navbar-fixed-top navbar-transparent"> <!--ナビゲーションバー, 背景白ベースのナビゲーションバーを使用, ナビゲーションバーを上部に配置, ナビゲーションバーを透明化-->
      <div class="container">
        <%= link_to root_path do %>
          <span><%= image_tag "icons/juventus_logo_3.png", class: "navbar-brand" %></span> <!--navbar-brandはブランドを表示-->
        <% end %>
        <ul class="nav navbar-nav navbar-right"> <!--navでナビゲーションバー(navbar-nav)を使用するという指定, ナビゲーションバーを右揃え-->
          <% if logged_in? %> <!--ログインユーザー用のリンク↓-->
            <li>
              <%= link_to favorites_index_path do %>
                <%= image_tag "icons/heart.png" %>
              <% end %>
            </li>
            <li>
              <%= link_to new_topic_path do %>
                <%= image_tag "icons/camera.png" %>
              <% end %>
            </li>
            <li>
              <%= link_to logout_path, method: :delete do %>
                <%= image_tag "icons/logout.png" %>
              <% end %>
            </li>
          <% else %> <!--ログインしていないユーザー用のリンク-->
            <li>
              <%= link_to new_user_path do %>
                <%= image_tag "icons/register.png" %>
              <% end %>
            </li>
            <li>
              <%= link_to login_path do %>
                <%= image_tag "icons/login.png" %>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
    
    <%= yield %>
    
    <script>
  　　$(function(){
    　　$(".alert").fadeOut(5000);
  　　});
　　</script>
    
  </body>
</html>